### ISSUE TITLE
FLASK_ENV' is deprecated 

### ISSUE THREAD

**Issue by ipapop** [candidtim/cookiecutter-flask-minimal#1]
Hello ,
First of all this a **wonderful agnostic cookiecutter for Flask 'by the book'**
I noted the following warning on makefile run:
FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
I corrected it in the makefile ,replacing FLASK_ENV=development with FLASK_DEBUG=1.
It worked for me but I don't know if this 'recommended' way to do it.
Thank you very much for this repository
Olivier

**Comment by candidtim** [comment]
You are right, thank you! Indeed,  Flask 2.2 [deprecated the `ENV`](https://flask.palletsprojects.com/en/2.2.x/config/?highlight=flask_debug#ENV) configuration variable. `DEBUG` is supported, and can be set with a `FLASK_DEBUG` environment variable or even with a command-line option:

    flask --app yourapplication --debug run

The template is updated for Flask 2.2 now, and uses the command-line option.
